// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20181030091630_Restructuredmodels")]
    partial class Restructuredmodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Bottle", b =>
                {
                    b.Property<int>("BottleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BottleType");

                    b.Property<bool>("IsProjectile");

                    b.Property<int>("LastPosX");

                    b.Property<int>("LastPosY");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("PosX");

                    b.Property<int>("PosY");

                    b.Property<DateTime>("SpawnTime");

                    b.Property<int>("Speed");

                    b.HasKey("BottleId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Bottle");
                });

            modelBuilder.Entity("Server.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MachineType");

                    b.Property<int>("PosX");

                    b.Property<int>("PosY");

                    b.Property<int>("SizeX");

                    b.Property<int>("SizeY");

                    b.HasKey("MachineId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("Server.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterClass");

                    b.Property<int>("Color");

                    b.Property<string>("Name");

                    b.Property<int>("Points");

                    b.Property<int>("PosX");

                    b.Property<int>("PosY");

                    b.Property<DateTime>("SpawnTime");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Server.Models.Bottle", b =>
                {
                    b.HasOne("Server.Models.Player")
                        .WithMany("Bottles")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
